apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: learn-microservice-ticketing-nodejs
build:
  local:
    push: false
  artifacts:
  - image: adhiana46/ticketing-nodejs-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: adhiana46/ticketing-nodejs-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: './**/*.js'
          dest: .
manifests:
  rawYaml:
  - infra/k8s/*
